apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: mern-todo
type: Opaque
stringData:
  JWT_SECRET: "thisisasecretkey"
  GMAIL_USERNAME: "your_email@gmail.com"
  GMAIL_PASSWORD: "your_gmail_app_password"
