name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    name: Test runner and kubectl access
    runs-on: [self-hosted, linux, x64, minikube]

    steps:
      - name: Check runner machine
        run: |
          hostname
          whoami
          pwd

      - name: Check kubectl access
        run: |
          kubectl get nodes
          kubectl get pods -n mern-todo
